apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;
        
        location / {
            try_files $uri $uri/ =404;
        }
    }
  
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Страница из ConfigMap</title>
        <style>
            body { 
                font-family: Arial, sans-serif; 
                margin: 40px; 
                background: #f5f5f5;
            }
            .container { 
                max-width: 800px; 
                margin: 0 auto; 
                background: white;
                padding: 30px;
                border-radius: 10px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            .header { 
                background: #4CAF50; 
                color: white;
                padding: 20px; 
                border-radius: 5px; 
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>Привет от Kubernetes!</h1>
                <p>Эта страница загружена из ConfigMap</p>
            </div>
            <h2>Статус приложения</h2>
            <p>✅ Nginx + Multitool успешно работают в Kubernetes Pod</p>
            <p>📁 Конфигурация управляется через ConfigMap</p>
            <p>🕒 Текущее время: <span id="datetime"></span></p>
            <hr>
            <h3>Компоненты приложения:</h3>
            <ul>
                <li>Nginx - веб-сервер</li>
                <li>Multitool - утилиты для диагностики</li>
                <li>ConfigMap - управление конфигурацией</li>
            </ul>
        </div>
        <script>
            document.getElementById('datetime').textContent = new Date().toLocaleString();
        </script>
    </body>
    </html>