apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: web-content
          mountPath: /usr/share/nginx/html
      
      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "8080"
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo 'Multitool is running'; sleep 30; done"]
      
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      
      - name: web-content
        configMap:
          name: nginx-config
          items:
          - key: index.html
            path: index.html