
{{- if .Values.ingress.tls }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-sc
  labels:
    revision: "{{ .Release.Revision }}"
    deployby: {{ .Release.Service }}
    tier: {{ .Values.labels.tier }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.crt }}
  tls.key: {{ .Values.ingress.tls.key }}
...
{{- end }}
