apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    task: one
    tier: homework
  namespace: task1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            limits:
              memory: "64Mi"
              cpu: "200m"
            requests:
              memory: "32Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
        - name: multitool
          image: praqma/network-multitool:alpine-extra
          resources:
            limits:
              memory: "64Mi"
              cpu: "200m"
            requests:
              memory: "32Mi"
              cpu: "100m"
          env:
            - name: HTTP_PORT
              value: "1181"
            - name: HTTPS_PORT
              value: "1443"
          ports:
            - name: http
              containerPort: 1181
              protocol: TCP
            - name: https
              containerPort: 2443
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 1181
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 1181
            initialDelaySeconds: 15
