apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy2
  namespace: task2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-init
  template:
    metadata:
      labels:
        app: nginx-init
    spec:
      initContainers:
      - name: wait-for-service
        image: busybox:1.36
        command: 
          - 'sh'
          - '-c'
          - |
            until nslookup svc2.task2.svc.cluster.local; do 
              echo "Waiting for service svc2..."; 
              sleep 3; 
            done
            echo "Service service_task2 is available!"
      containers:
      - name: nginx
        image: nginx:1.24.0
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
          requests:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 80