apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
  namespace: task1
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      port: 8081
      targetPort: 8081
    - name: multitool
      port: 8080     
      targetPort: 8080 
  type: ClusterIP