apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
  namespace: task1
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      port: 8080
      targetPort: 80
    - name: multitool-http
      port: 9080
      targetPort: 1181
    - name: multitool-https
      port: 9443
      targetPort: 2443
  type: ClusterIP