labels:
  tier: homework

replicaCount: 1

containers:
  image: nginx
  name: nginx
  tag: ""
  port: 80

resources:
  limits:
    memory: "128Mi"
    cpu: "500m"
  requests:
    memory: "64Mi"
    cpu: "250m"

svc:
  port: 80
  type: ClusterIP

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls: 
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHVENDQWdHZ0F3SUJBZ0lVS1UxVldHRlR2RENvOXpReGpBcTQ1NUZQNnE4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hERWFNQmdHQTFVRUF3d1JiWGxoY0hBdVpYaGhiWEJzWlM1amIyMHdIaGNOTWpVeE1ERTBNRGN4TVRRNQpXaGNOTWpZeE1ERTBNRGN4TVRRNVdqQWNNUm93R0FZRFZRUUREQkZ0ZVdGd2NDNWxlR0Z0Y0d4bExtTnZiVENDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2UxTXROczI1aEVLZVZzckhOSFMwaGMKb3d4R2o4NnRvdGtuM2JJc09PR09PajAzclZDNzZZTmIrbEtod214TWZlR1hjZVVhbVRhWC9IV0EzdVZZR2xyQgptaWp2K3QzWXdGU1E0SWx6UmV5MjFxUzJWajNJaENmQXZXeE9wbTczSXJ6OTYweXpMY3F3NjRyN0JZZW0rajV0CjVpWHAwVEpWQTNSL3NON2grQWk0RkdJOWNHWWZyV0F6UzB4MDJydWJwRUtNRXlnVG1tb0VraWFhUk40N1g4RlkKajJCckpGNk80d1BGaWRtNmZFME9aRFpDZ1JFRmUxRFU3TmovQ1dxam4yT0xQaXJsbURFS1BGTUhUNFA4b0JuVgpQK244MHdqMHhjVTNVbTFwYnpXQzBoUzBuYytWbU40MnVTVlFZUWFiVUtGYmVrQVlMcUZ5UUpUaTJsZ0xJQWNDCkF3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZFZkNqdjNKVmJDS0FZM1lCZ2l0Z053U3ZZWnlNQjhHQTFVZEl3UVkKTUJhQUZFZkNqdjNKVmJDS0FZM1lCZ2l0Z053U3ZZWnlNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUFJQmkwNGFWaGFUWUYvVVF2RXl1YW9GNWFoRmN0YzQrL1p1S05ldVEzdVU3REJ6CkpvbGdEVGE4STNVWXdybEVUdTlwY2h5WVJzc0Z4MWxNd2Y1am1UMElHZ09Hd0c3TGhnbHc2T3ZWTjdzaVVaZVIKWFlpNU5qUkh6VEcxV0V5aG9KNFl1bENQSE9kaWdZSWU4bWFhaWJRdzVDUDR1aEMrQmlLRkZURHJycmZ5bEt2awp6Y0thTEh2RXY0blZnTG5FWTRBNHExbUtRTklyNlU2QXo4NUdndTV2NWtFN3paRE9lM0V5Y0NEMXFEaG0xQkpICk81SVlmOW1GK2tKaWZmSU5TK1lXT0pDaEJkWi9nV1plVmZiaGwxNHVHVkRSQng5dGNkSTVtSUt5cE9NOEdGZFUKZFR0Qll1VXAxN0pMN0QxanRoNHZuOC9VaFpEY0ozc3BaZ0Z2bDVjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ250VExUYk51WVJDbmwKYkt4elIwdElYS01NUm8vT3JhTFpKOTJ5TERqaGpqbzlONjFRdSttRFcvcFNvY0pzVEgzaGwzSGxHcGsybC94MQpnTjdsV0JwYXdab283L3JkMk1CVWtPQ0pjMFhzdHRha3RsWTl5SVFud0wxc1RxWnU5eUs4L2V0TXN5M0tzT3VLCit3V0hwdm8rYmVZbDZkRXlWUU4wZjdEZTRmZ0l1QlJpUFhCbUg2MWdNMHRNZE5xN202UkNqQk1vRTVwcUJKSW0KbWtUZU8xL0JXSTlnYXlSZWp1TUR4WW5adW54TkRtUTJRb0VSQlh0UTFPelkvd2xxbzU5aml6NHE1Wmd4Q2p4VApCMCtEL0tBWjFUL3AvTk1JOU1YRk4xSnRhVzgxZ3RJVXRKM1BsWmplTnJrbFVHRUdtMUNoVzNwQUdDNmhja0NVCjR0cFlDeUFIQWdNQkFBRUNnZ0VBSmFzTlAyK3o0djlzYVp0L0lHVmpBMTNMUVhhWDFsUXB2NXkwcnRBLzltbDcKcTBSV0tVd0xwdldCeEEyUkhjSVFoQnIvK2ZWL2RFT3U4TFdCV3dIdTZYT1NySjg2T1puMW1RanhaZTMrUnF6SwppVFJyS25WZk9ZNlEvVUt0SHo5akRnLzZTYi8xQ1JHejFnT0x1bXhHeUw3bWNwMlIzenc1Q25HanlHdjR5Znd4CmcxcSticmNicS84aVZtak01THpNT01CRlZkYndJUWpGREE0TkhYUW5oNityK0tWTERSanMxM2dYQkplb0dXZVEKRTZlQUMyTVpvaGNPdlBMS1Q5N0YxUlZsR09wdDFYWXc4K3BNK2krV3BQckhZNGpQeGNDL3Irano2ZFFmYUtpUQo1MG5YMXNTdjlMTm5PU0k2aHVBaGdrZmVlQlltZktIV2RRUEdWb29NQVFLQmdRRFA2cW9XejlRSm1SYWJnM0YzCjd3anRuSkZLN0grWmFhNnY3T21aV3U5Nm5GU1dSdzBObXZ0SkxOaDI2UkRlY1V1eXZYbUxUdFhnNEx5UHhSeFMKTGptOWRsc3k2bnhmQjRiT2tZNS9tQnlrZHdLckt1VVdUT1lwMU5YUnIvdUVFUnhpQk5SVlNzQUNmNGJYK01CMApkLy9SZXlxeGhkUnJDRmI5Qm85Q085b205UUtCZ1FET2ZncHFIa1RINWMraktzUnhDSUpIaHBqZUcrdlVub0xiCkwxY3dVa3pyNVNzazYyNjRaRmVhSEdmUU54WHE2eEljYUR4ZnVjaVBONWlnb0JvOTNqUVVPWU9mbUJKSjNCWTkKS1ovQTBUaTcxYmcxbkU1L1E0K2dxSEIyWlZ2eS9VNFFFSVlrVlpjajEyVFI3aEZBYnZxRUhhMzlDcG9NdTNkUQpnOXBhYjJKMWl3S0JnUUN0SGc4UmYycGxzM29IY3FKLzRoL2srSUJoaWhtVWUxSmdXVHNIM1plWTE2SDJucUpYCnVidVJhaTJ5bE16ZTZpYkZaTTVYR0FVdGdQS0FJdmM1MWhOdGxhYko5a1FvTy9RYSswZFRKaXh6SkVTc2tNSysKbHJqdUM3RWRMeEtWSEVvdHN5ZTQvTXh6U0F2V3QrQkhHY04vZ0xaRHFkTDhhNjFDY0x2SHdsNGFJUUtCZ1FDUwpYb2VWVnlWY0tRdDQxcHp1bnFCeWdQY2xJZGVXSEZJWGVrUXNiWG8zRUhmM3NLY0lMNkJsRGxPTUpTLzFHSEg3CkR1d1Uwc1ZXdDRzSitOTUJIZHYrcGhJbDg0NnJLa1hkVHY3OWw1REduS1Q1NDNWRkFxZnhzdFFkS0pYMzlSUDcKa1NyMDRITEZKaTVDSEtXLzdhcklNWjJlSzRDdEc4bGtta0lTTHJnMUp3S0JnQklOdjZwQzQyeng5UXlVRVFpWgpXVHNaVExQbFJiKy9qQUxHK3VOM1dST3NaUzhYQ3lKZzB6TzhUeHBkelU2OWxhZFExR0FnZVFxOTdRWlJlT0RBCnJvYTJoSnJPcFhROGZ5b0kwTXFEc0xTV2pCMk81bzNzdnJXdmFjbjkzTXE4RHE0L3ViZytaQmRCWVpJclMrVUoKTk0zQzhhMHVCQzJMU21CVzg1N3ExSlJtCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K