---
apiVersion: v1
kind: Pod
metadata:
  name: echoserver
  namespace: default
  labels:
    app: echoserver
    comment: task1.1
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "500m"
    ports:
    - name: http
      containerPort: 8080
    - name: https
      containerPort: 8443
...
