---
apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: netology-web
    comment: task2.1
  namespace: default
spec:
  containers:
  - name: netology-web
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "500m"
    ports:
    - name: http
      containerPort: 8080
    - name: https
      containerPort: 8443
...
