#cloud-config
write_files:
  - path: /etc/hostname
    content: ${node_hostname}
  - path: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
  - path: /etc/sysctl.d/99-kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

runcmd:
  # Установка hostname
  - hostnamectl set-hostname ${node_hostname}

  # Настройка IPv4 forwarding
  - echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
  - sysctl -p

  # Загрузка модулей ядра
  - modprobe overlay
  - modprobe br_netfilter

  # Базовая настройка
  - apt-get update
  - apt-get install -y curl wget vim htop net-tools

  # Добавление записей в /etc/hosts для всех нод
  - echo "192.168.10.10 k8s-master" >> /etc/hosts
  - echo "192.168.10.20 k8s-worker-1" >> /etc/hosts
  - echo "192.168.10.21 k8s-worker-2" >> /etc/hosts
  - echo "192.168.10.22 k8s-worker-3" >> /etc/hosts
  - echo "192.168.10.23 k8s-worker-4" >> /etc/hosts

final_message: "Base node setup complete for ${node_hostname}. Ready for Kubernetes installation."